enrich_insight:
  form_lookback_weeks: 2
  captaincy_tiers:
    Gods:
      players:
      - Haaland
      - B.Fernandes
      - Bruno Fernandes
      coefficient: 1.2
    Demigods:
      players:
        - Semenyo
        - "João Pedro"
        - Gabriel
        - Saka
        - Palmer
        - Thiago
      coefficient: 1.08
pyomo_solver:
  thrift_factor: 0.001
  bench_potency_epsilon: 1.0e-05
  form_factor_weight: 0.7
  red_zone_threshold: 1290
  red_zone_limit: 5
  spp_scores:
    Penalties:
      primary: 5.0
      secondary: 2.5
    Direct Free Kicks:
      primary: 2.5
      secondary: 1.25
    Corners & Indirect Free Kicks:
      primary: 1.5
      secondary: 0.75
temporal_discounting:
  fixture_weights:
  - 1.0
  - 0.5
  - 0.3
  - 0.2
  - 0.1
